history/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", view=views.index, name="index"),
]

logger/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    # Logger
    path("log", view=views.call_log),
    path("", view=views.index, name="index"),
]

noc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("reportgen/", include(("reportgen.urls", "reportgen"), namespace="reportgen")),
    path("history/", include(("history.urls", "history"), namespace="history")),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("", include(("logger.urls", "logger"), namespace="logger")),
]

reportgen/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", view=views.index, name="index"),
]

logger/models.py
from django.db import models

# Create your models here.
class CallLog(models.Model):
    extn = models.IntegerField()
    fullname = models.CharField(max_length=100)
    budget = models.CharField(max_length=20)
    destination = models.CharField(max_length=100)
    is_official = models.BooleanField(default=True)
    is_international = models.BooleanField(default=True)
    time_booked = models.DateTimeField(null=True)
    time_connected = models.DateTimeField(null=True)
    time_finished = models.DateTimeField(null=True)
    remark = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.fullname}({self.extn}) called {self.destination} - {self.remark}"

reportgen/models.py
from django.db import models

# Create your models here.

history/views.py
from django.db.models import Q
from django.shortcuts import render
from logger.models import CallLog

# Create your views here.
def index(request):
    logs = CallLog.objects.all()
    filtered = False

    query = request.GET.get("q")
    if query:
        logs = logs.filter(
            Q(fullname__icontains=query)
            | Q(extn__icontains=query)
            | Q(budget__icontains=query)
            | Q(destination__icontains=query)
        )
        filtered = True

    return render(
        request,
        "history/index.html",
        {"logs": logs.order_by("-id"), "filtered": filtered},
    )

logger/views.py
import json

from django.http.response import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from datetime import datetime
from . import models

# Create your views here.
@login_required
def index(request):
    """Index page of the logger app."""
    return render(request, "logger/index.html")


@login_required
def call_log(request):
    if request.method == "POST":
        """Save log to the database"""
        data = json.loads(request.body)

        # convert the timestamps to datetime
        timestamp_booked = data["time_booked"]
        timestamp_connected = data["time_connected"]
        timestamp_finished = data["time_finished"]

        data["time_booked"] = datetime.fromtimestamp(timestamp_booked) if timestamp_booked else None
        data["time_connected"] = datetime.fromtimestamp(timestamp_connected) if timestamp_connected else None
        data["time_finished"] = datetime.fromtimestamp(timestamp_finished) if timestamp_finished else None

        (
            extn,
            fullname,
            budget,
            destination,
            is_official,
            is_international,
            time_booked,
            time_connected,
            time_finished,
            remark,
        ) = data.values()

        call_details = models.CallLog(
            extn=extn,
            fullname=fullname,
            budget=budget,
            destination=destination,
            is_official=is_official,
            is_international=is_international,
            time_booked=time_booked,
            time_connected=time_connected,
            time_finished=time_finished,
            remark=remark,
        )
        call_details.save()

        return HttpResponse("OK", status=201)

reportgen/views.py
from django.shortcuts import render
from logger.models import CallLog
from datetime import datetime, timedelta
from openpyxl import Workbook
from django.http import HttpResponse
from tempfile import NamedTemporaryFile

rate = 12.0

# Create your views here.
def index(request):
    report_range = request.GET.get("range")

    if report_range.strip() == "":
        report_range = "weekly"

    report_range = report_range.lower()
    since = None
    if report_range == "weekly":
        today = datetime.today()
        since = today - timedelta(days=today.weekday())
        since = since.replace(hour=0, minute=0, second=0, microsecond=0)
    elif report_range == "monthly":
        # get the timestamp of the first day of the month
        today = datetime.today()
        since = datetime(today.year, today.month, 1)

    # get all call logs since 'since'
    call_logs = CallLog.objects.filter(time_booked__gte=since)

    wb = Workbook()
    ws = wb.active  # active sheet

    # insert headers
    ws.append(["Date", "Description", "Amount", "Currency"])

    i, j = 2, 1
    # walk through all call logs, and add them to the sheet
    for call_log in call_logs:
        ws.cell(row=i, column=j).value = date_of(call_log.time_booked)

        description = f"{call_time_of(call_log)} {''.join(call_log.destination.split(' '))} {call_log.fullname}"

        ws.cell(row=i, column=j + 1).value = description

        ws.cell(row=i, column=j + 2).value = call_time_of(call_log) * rate
        ws.cell(row=i, column=j + 3).value = "NGN"
        i += 1

    # send the file to the browser
    response = HttpResponse(
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    response["Content-Disposition"] = "attachment; filename=report.xlsx"
    with NamedTemporaryFile() as tmp:
        wb.save(tmp.name)
        tmp.seek(0)
        response.write(tmp.read())
    return response


def date_of(timestamp):
    return timestamp.strftime("%d-%m-%y")


def call_time_of(log):
    if log.remark.lower() != "success":
        return 0
    time_conn = log.time_connected
    time_fin = log.time_finished
    # return the difference between the two times in minutes
    call_time = (time_fin - time_conn).seconds // 60
    if call_time <= 0:
        return 1
    return call_time

history/templates/history/index.html
{% extends "base.html" %}

{% load static %}

{% block src %}
    <!-- Tailwind deps -->
    <link href="{% static 'history/dist/tailwind.min.css' %}" rel="stylesheet">
    <!-- Entry script -->
    <script type="module" src="{% static 'history/main.js' %}"></script>
{% endblock %}

{% load custom_tags %}

{% block content %}
    
<div class="flex flex-col bg-gray-50">
  <form action="{% url 'history:index' %}" method="get" class="mx-32 my-4 h-12 flex justify-center items-center rounded">
    <input type="text" class="h-full px-4 w-4/5 border-2 border-blue-200 rounded" placeholder="Search" name="q">
    <div class="mx-2 w-1/5 flex justify-start items-center h-full">
      <input class="bg-blue-500 hover:bg-blue-700 text-white text-center py-2 px-4 rounded" type="submit" value="Search"/>
    </div>
  </form>

  {% if filtered %}
  <div class="m-auto my-4 flex items-center">
    <span>You are viewing {{logs|length}} results • </span>
    <a href="{% url 'history:index' %}" class="mx-2 text-center font-medium text-blue-500 hover:text-black cursor-pointer">Clear</a>
  </div>
  {% endif %}

  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Caller
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Destination
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Budget
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Call Time
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Date
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Remark
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            {% for log in logs %}
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="flex justify-center items-center flex-shrink-0 h-10 w-10 rounded-full bg-blue-200 font-medium">
                    <span>{{ log.fullname|initials }}</span>
                  </div>
                  <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                        {{ log.fullname }}
                    </div>
                    <div class="text-sm text-gray-500">
                        {{ log.extn }}
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ log.destination }}</div>
                <div class="text-sm text-gray-500">{% if log.is_international %} International ✈ {% else %} Local {% endif %}</div>
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ log.budget }}</div>
                <div class="text-sm text-gray-500">{% if log.is_official %} Official 💼 {% else %} Personal {% endif %}</div>
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{ log | get_call_time }}
              </td>

              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{ log | get_call_date }}
              </td>

              <td class="px-6 py-4 whitespace-nowrap">
                <span class="mx-auto px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-{{ log.remark|rmkcolor }}-500 text-white">
                    {{ log.remark }}
                </span>
              </td>

              {% if user.is_authenticated %}
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <a href="{% url 'admin:index' %}logger/calllog/{{log.id}}/change" class="text-blue-600 hover:text-blue-900">Edit</a>
                </td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

logger/templates/logger/index.html
{% extends "base.html" %}

{% load static %}

{% block src %}
    <!-- Vue and Tailwind deps -->
    <link href="{% static 'logger/dist/tailwind.min.css' %}" rel="stylesheet">
    <script type="module" src="{% static 'logger/dist/vue.esm-browser.js' %}"></script>
    <!-- Entry script -->
    <script type="module" src="{% static 'logger/main.js' %}"></script>
{% endblock %}

{% block content %}
    <div id=app></div>
{% endblock %}

noc/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Inject page entry src -->
    {% block src %}{% endblock %}

    <link href="{% static 'logger/dist/tailwind.min.css' %}" rel="stylesheet">

    <title>NOC Call Logger</title>
</head>

<body>
    <nav class="h-12 flex align-center justify-end bg-gray-50">
        <ul class="space-x-8 mx-4 flex items-center">
            <li><a class="hover:underline" href="{% url 'logger:index' %}">Logger</a></li>
            <li><a class="hover:underline" href="{% url 'history:index' %}">Call History</a></li>
            <li><a id="report-gen" class="hover:underline" href="#">Generate Report</a></li>
            <li><a class="hover:underline" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="hover:underline" href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </nav>

    <!-- Inject page HTML content -->
    {% block content %}{% endblock %}

    <!-- report generation -->
    <div class="fixed hidden inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full" id="my-modal">
        <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
            <div class="mt-3">
                <h3 class="px-4 text-lg leading-6 font-medium text-gray-900">Generate Report</h3>
                <form action="{% url 'reportgen:index' %}" method="get" class="items-center px-4 py-3">
                    <input type="radio" name="range" value="weekly" id="weekly" class="my-2 form-radio" checked>
                    <label for="weekly">Weekly Report</label>
                    <br>
                    <input type="radio" name="range" value="monthly" id="monthly" class="form-radio">
                    <label for="monthly">Monthly Report</label>

                    <div class="flex">
                        <button id="close-btn"
                            class="my-4 px-4 mx-1 py-2 bg-red-500 text-white text-base font-medium rounded-md w-full shadow-sm hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-300">Close</button>
                        <button type="submit" id="download-btn"
                            class="my-4 px-4 mx-1 py-2 bg-blue-500 text-white text-base font-medium rounded-md w-full shadow-sm hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300">
                            Download
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        let modal = document.getElementById("my-modal");
        let closeBtn = document.getElementById('close-btn');
        let reportgen = document.getElementById('report-gen');

        reportgen.addEventListener('click', function () {
            modal.classList.remove('hidden');
        });

        closeBtn.addEventListener('click', function (e) {
            modal.classList.add('hidden');
            e.preventDefault()
        });
    </script>
</body>

</html>

noc/templates/login.html
{% load static %}
<html>

<head>
    <link href="{% static 'logger/dist/tailwind.min.css' %}" rel="stylesheet">
</head>

<body>
    <form class="w-full h-full flex justify-center" method="post" action="{% url 'login' %}">
    {% csrf_token %}
        <div class="md:w-1/3 flex flex-col justify-center align-center text-center">
            <label class="block text-3xl font-bold text-gray-900 my-8">Log in to your account</label>

            <input class="w-full p-2 border border-gray-400 border-b-1 rounded-t-lg" type="text" name="username" placeholder="Username" required>

            <input class="w-full p-2 border border-gray-400 border-t-0 rounded-b-lg" type="password" name="password" placeholder="Password" required>

    {% if form.errors %}
    <p class="text-red-500">Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
    {% if user.is_authenticated %}
    <p class="text-red-500">Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p text-red-500>
    {% else %}
    <p class="text-red-500">Please login to see this page.</p>
    {% endif %}
    {% endif %}

            <button type="submit" class="my-8 group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                    <svg class="h-5 w-5 text-blue-500 group-hover:text-blue-400" x-description="Heroicon name: solid/lock-closed" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path>
                    </svg>
                </span>
                Login
          </button>
        </div>
    </form>
</body>
</html>

reportgen/templates/reportgen/index.html
{% extends "base.html" %}

{% load static %}

{% block src %}
    <!-- Tailwind deps -->
    <link href="{% static 'history/dist/tailwind.min.css' %}" rel="stylesheet">
{% endblock %}

{% load custom_tags %}

{% block content %}
  <p>Empty</p>
{% endblock %}  